jenkins:
  systemMessage: "Jenkins managed via Configuration as Code\n"

  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "{{ jenkins_admin_user }}"
          password: "${readFile:/run/secrets/admin_password}"

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousJobStatusPermission: false