---
# ----------------- CD key ------------------
- name: Dodaj klucz SSH do autoryzacji na VM2
  ansible.posix.authorized_key:
    user: ubuntu
    state: present
    key: "{{ lookup('file', jenkins_cd_public_key_path) }}"

- name: Upewnij się, że git jest zainstalowany
  ansible.builtin.apt:
    name: git
    state: present

- name: Sklonuj/zaktualizuj repozytorium appki
  ansible.builtin.git:
    repo: "{{ app_repo_url }}"
    dest: "{{ app_dest }}/src"
    version: master

- name: Wyrenderuj docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ app_dest }}/docker-compose.yml"
    mode: "0600"

- name: Zbuduj obraz i uruchom stack (app + db)
  community.docker.docker_compose_v2:
    project_src: "{{ app_dest }}"
    build: policy
    state: present
