---
- name: Stworz folder docelowy dla plikow jenkins
  ansible.builtin.file:
    path: "{{ jenkins_home }}"
    state: directory
    mode: "0744"

- name: Kopiuj plik dockerfile z repo do miejsca docelowego
  ansible.builtin.copy:
    src: files/Dockerfile
    dest: "{{ jenkins_home }}/Dockerfile"

- name: Kopiuj skrypt init-admin.groovy do kontekstu budowania
  ansible.builtin.copy:
    src: files/init-admin.groovy
    dest: "{{ jenkins_home }}/init-admin.groovy"

- name: Kopiuj plik zawierający pluginy
  ansible.builtin.copy:
    src: files/plugins.txt
    dest: "{{ jenkins_home }}/plugins.txt"

# ----------------JCasC  config ------------------
- name: Stwórz folder na sekrety
  file:
    path: "{{ jenkins_home }}/secrets"
    state: directory
    mode: "0700"

- name: Kopiuj sekrety do jenkins secrets
  copy:
    dest: "{{ jenkins_home }}/secrets/{{ item.key }}"
    content: "{{ item.value }}"
    mode: "0600"
  no_log: true
  loop: "{{ jenkins_secrets | dict2items }}"

- name: Kopiuj plik JCasC
  ansible.builtin.copy:
    src: files/jenkins.yaml
    dest: "{{ jenkins_home }}/jenkins.yaml"

- name: Zbuduj obraz z podstawowego pliku Dockerfile
  community.docker.docker_image:
    name: "{{ jenkins_image_tag }}"
    source: build
    force_source: true
    build:
      path: "{{ jenkins_home }}"

- name: Uruchom kontener 
  community.docker.docker_container:
    name: jenkins
    image: "{{ jenkins_image_tag }}"
    restart_policy: unless-stopped
    ports: 
      - "{{ jenkins_port }}:8080"
    volumes:
      - jenkins_home:/var/jenkins_home # Named volume for app data
      - /var/run/docker.sock:/var/run/docker.sock
      - "{{ jenkins_home }}/secrets:/run/secrets:ro" # bind volume nie ppowinno być też w var ? 
    state: started
    env:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
      CASC_JENKINS_CONFIG: /run/secrets/jenkins.yaml

