{
 "title": "DevOps Overview - appka + VM-ki",
 "tags": [ "devops-projekt" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Request rate appki (req/s, per handler)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 24, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (handler) (rate(http_requests_total[1m]))",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Zużycie CPU (%) per VM",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 24, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (role) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "Zużycie RAM (%) per VM",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 16, "w": 24, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100",
     "legendFormat": "{{role}}"
    }
   ]
  }
 ]
}