---
- name: Konfiguracja bazowa serwerów
  hosts: all
  roles:
    - docker
    - ufw
    - node-exporter

- name: Postaw kontener docker aplikacji
  hosts: app
  roles:
    - deploy-app

- name: Postaw kontener docker ci
  hosts: ci
  roles:
    - deploy-jenkins

- name: Postaw stack Prometheus + Grafana
  hosts: monitoring
  roles:
    - deploy-monitoring

