---
- name: Konfiguracja bazowa serwerów
  hosts: all
  roles:
    - docker
    - ufw

- name: Postaw kontener docker aplikacji
  hosts: app
  roles:
    - deploy-app

- name: Postaw kontener docker ci
  hosts: ci
  roles:
    - deploy-jenkins